microsoft/pxt-ev3

- docs/offline.md
Bring in the extended offline page for linking to the offline-app page.
Note: the extended section will appear at the top when this target matches current pxt:
https://github.com/Microsoft/pxt/pull/5285
RE: https://github.com/Microsoft/pxt-microbit/pull/1853#issuecomment-470327378
> Add in extended offline page

- libs/core/input.ts
When detecting multiple UART devices, the second device triggers a UART reset in the detect device loop because the status is "changed".
Applying all UART device changes at once in this change.
Note that this does not fix the underlying issue that we crash when the UART configuration changes (e.g. connecting or disconnecting sensors on the fly). I will investigate further to see if this can be fixed too.
> Multi sensor fix

- docs/reference/motors/synced/steer.md
- docs/reference/motors/synced/tank.md
- sim/state/motornode.ts
- sim/state/output.ts
Fix simulator to match hardware behavior: only 1 set set of synched motors at any time.
https://github.com/microsoft/pxt-ev3/issues/854
> Single tank

- libs/core/output.ts
Add a pause(1) for motors.run command (we already pause when a distance is provided)
> add a run to avoid tight loop hogging

- libs/color-sensor/color.ts
- libs/core/buttons.ts
- libs/core/input.ts
- libs/core/linux.cpp
- libs/gyro-sensor/gyro.ts
- libs/infrared-sensor/ir.ts
- libs/touch-sensor/touch.ts
- libs/ultrasonic-sensor/ultrasonic.ts
Preparing for GC support: no more unsafe polling and support for tight loops.
With this changes, the following tight loop works:
```
console.sendToScreen()
sensors.touch1.onEvent(ButtonEvent.Pressed, function () {
console.log("pressed")
})
console.log("start forever")
motors.largeBC.run(50)
while (!sensors.touch1.isPressed()) {
}
console.log("run")
motors.stopAll()
console.log("stopped")
```
> Safepolling

- libs/screen/targetoverrides.ts
Show ports runs in background until another render command takes over.
Fix for https://github.com/microsoft/pxt-ev3/issues/823
> background show ports

- editor/deploy.ts
- editor/wrap.ts
Mac does not like to immediately close the serial port - it locks the brick.
> add delay to fix mac deployment

- libs/core/linux.cpp
We have a race with the esc button where the program starts the motors while we are exiting .
> lock execution thread before exiting

- libs/core/output.ts
- sim/state/motornode.ts
- sim/state/output.ts
the LEGO firmware is inconsistent w.r.t. to polarity support. Implement support in typescript instead.
```
brick.buttonEnter.onEvent(ButtonEvent.Pressed, function () {
motors.stopAll()
})
brick.buttonLeft.onEvent(ButtonEvent.Pressed, function () {
motors.largeB.setInverted(false)
motors.largeB.run(50)
})
brick.buttonUp.onEvent(ButtonEvent.Pressed, function () {
motors.largeBC.setInverted(false)
motors.largeBC.run(50)
pause(1000)
motors.largeBC.steer(0, 50)
})
brick.buttonRight.onEvent(ButtonEvent.Pressed, function () {
motors.largeB.setInverted(true)
motors.largeB.run(50)
})
brick.buttonDown.onEvent(ButtonEvent.Pressed, function () {
motors.largeBC.setInverted(true)
motors.largeBC.run(50)
pause(1000)
motors.largeBC.steer(0, 50)
})
```
> polarity in synched motor

- docs/tutorials/touch-sensor.md
The "Stop at Object" page isn't formatted as a tutorial. So, change it's card type to `example` or make it into a tutorial?
Some history here:
https://github.com/microsoft/pxt-ev3/commits/master/docs/tutorials/touch-sensor.md
> Change card type for 'Stop at Object'

- editor/wrap.ts
I'm seeing lot of timeout errors when trying to send project via bluetooth. In most cases they occur at second and consecutives tries. Changing timeout to 5s eliminated this issues completely. I'm not sure if this is an issue with some slowness on my PC or my brick, but 5s still seems resonable to remove false positives. I did not encounter any errors after changing timeout value.
> Change timeout 1s -> 5s to reduce Timeout errors

- libs/core/output.ts
When set to reverse, the ange method does not return the correct value. The value is inverted.
For example, I connected two medium motors to the ev3 for the chassis.
One set the reverse. When I use propulsion techniques for motors, they spin correctly. But the one that, with reverse, gives angle with a minus, although the motor is spinning forward (as needed).
In my algorithm for moving along a line at a distance, ange () had to be multiplied by -1 for a motor with a reverse.
> fix invert motor angle metod

- pxtarget.json
These blocks are present in the stable version, but not in the beta.
> Return break and continue loops blocks

- theme/style.less
Return the background color of the selected element in the editor toggle.
It was before the change...
After changing...
> Return background color of selected element in editor toggle

- libs/screen/targetoverrides.ts
When the program starts, when the showBoot() function is launched, the screenMode is checked and the showPorts function is launched, which in turn executes the renderPorts() function in a loop. While renderPorts is running, the screenMode may change, for example to ShowLines (when showString() was run). It may turn out that the mode has changed, and the renderPorts method has not been fully executed ... in the future, it will draw its own graphics on the screen, although we do not expect to see them already, because. a regime change has occurred. I added checks inside the function before displaying.
before changes
> RenderPorts extra checks before print

- fieldeditors/field_music.ts
The problem has existed for a long time, icons for elements with music are not displayed.
If you look, then in Russian an undenfined error appears in the console.
```buttonImg.src = this.getSoundIcon(category);```
Here are some examples. English language.
That's it in Russian.
(These are pictures from the beta version.)
The problem was that if you enable another language on the site (for example, Russian), then the options values were taken with a translation in the selected language. They didn't match the category values (in English) in icons.jres.
1) Therefore, I decided to change it so that options sorting is disabled so that options do not change places in different languages.
2) Next, I from the initially obtained values
```soundIconCache = …
```
> Fix music images items in other languages

- libs/color-sensor/color.ts
- sim/state/color.ts
- sim/visuals/board.ts
- sim/visuals/controls/colorWheel.ts
- sim/visuals/nodes/colorSensorView.ts
Code that adds reflection raw support for the color sensor. The range of values for this is from 0 to 1023, because analog to digital converter is 10 bits. In fact, the color sensor gives values ​​of about 400 - 700, but I decided to leave the range, which could theoretically be. For other cases (reflections and ambient lighting), the range remains from 0 to 100. The average value when setting the mode in the simulator is displayed as 512, for other modes 50%.
> Added support for Reflection Raw mode for the color sensor to the simulator

- libs/screen/targetoverrides.ts
Similar blocks have been created, in which the ability to select the place to print horizontally (columns) has been added, as well as the choice of printing mode black text on a white background and white text on a black background.
Old blocks are deprecated.
> Extended show screen blocks options

- fieldeditors/field_color.ts
- libs/color-sensor/ns.ts
- sim/visuals/controls/colorGrid.ts
Add a void option to the simulator for the color sensor.
Now emptiness can be chosen non-intuitively. There is no option. But, if you click on the circle with the selected color again, then the none option is activated, I think that this is not clear to users, so I added a separate circle.
> Add a none option to the simulator for the color sensor and colorEnumPicker extension

- sim/visuals/controls/colorGrid.ts
A typo that hadn't been noticed before. Does not affect the operation of the simulator.
before
> Сhange gray to brown in simulator circle class

- libs/color-sensor/color.ts
- libs/core/input.ts
- libs/screen/targetoverrides.ts
- sim/dalboard.ts
- sim/state/color.ts
- sim/state/sensor.ts
- sim/state/uart.ts
- sim/visuals/board.ts
- sim/visuals/controls/colorRGBWheel.ts
- sim/visuals/controls/colorWheel.ts
- sim/visuals/nodes/colorSensorView.ts
Added simulator support for RGB raw color sensor mode. To do this, I had to change the input code from the sensors and the color sensor code. Prior to this, there was no support for the fact that you can get an array of values.
> RGB raw color sensor simulator support

- theme/style.less
At certain screen resolutions, jumps occur in the simulator.
This created an annoyance when the simulator jumped due to the vertical scroll bar appearing and disappearing.
Temporary solution before ptx-core is upgraded to at least v8.2.7.
https://github.com/microsoft/pxt/commit/84e896cbcadf8a78479a0867f5bc6dd53d0458a8
> Sim scrollbar jump fix

- libs/color-sensor/color.ts
- libs/core/input.ts
When changing the mode to Reflection Raw, I noticed that you can get inadequate ones. These numbers are greater than 1023, which cannot be at all. Something like 40 thousand.
I even recorded a video with this problem.
https://photos.app.goo.gl/ZKhqqND3uNrmJhPs5
I decided to write an algorithm inside the function for setting the operating mode. Valid only when the mode is changed once.
At first I just made the algorithm so that it simply ignored values greater than 1023, but then I remembered about other modes (reflection and external environment from 0 to 100, and color mode from 0 to 7). But later I realized that ignoring values greater than 1023 is not enough, because. we can get the values from the previous mode from the color sensor, this is from 0 to 100 (since at startup, the …
> Changes in mode change for color sensor

- editor/deploy.ts
1. Add baudRate property and assign it with existing baudrate on connect.
2. Read full packet from brick instead random one.
Corrected the code that was written by dmitryaleshin.
https://github.com/microsoft/pxt-ev3/pull/1031
> Bluetooth upload fix

- libs/core/output.ts
Added use of the invertedFactor() method in the speed() method. Done in the same way as for the case of the angle() method.
Before change
After the change
But the simulator itself still uses getMotorData(), which does not take into account motor inversion. Therefore, the value of the speed or angle with a minus is displayed there. I could not add invertedFactor() to getMotorData() for a specific motor, because the simulator immediately starts displaying motors that are not used in the program.
Changes like this...
https://github.com/microsoft/pxt-ev3/pull/999
> Motor speed invertedFactor usage

- libs/screen/targetoverrides.ts
A block that can clear multiple lines at once. In general, it is necessary so that in the screen output cycle, first clearing, and then printing ten lines, flickering occurs on the screen because screen output is not a fast operation. Therefore, I think that it is better to clear some lines first before outputting to them.
I would indicate the default values of the array, but as I understand it, pxt-core does not support such an option.
> Screen clear lines block

- theme/style.less
The first change returns the background pattern as in the stable version.
The second change is to fix #downloadArea overlapping on the simulator. I don’t really understand why this bug is visible only in pxt-ev3. This bug is not detected in microbit, but the #downloadArea field is also larger than the height of #editortools itself. I compared the properties, but they seem to be all the same.
It was and became
> Editor display changes

- libs/color-sensor/color.ts
- libs/core/buttons.ts
- libs/core/indicator.ts
- libs/core/input.ts
- libs/core/pxt.json
- libs/ev3/brick.ts
- libs/ev3/ns.ts
- libs/gyro-sensor/gyro.ts
- libs/infrared-sensor/ir.ts
- libs/screen/targetoverrides.ts
- libs/touch-sensor/touch.ts
- libs/ultrasonic-sensor/ultrasonic.ts
- package.json
- targetconfig.json
- theme/style.less
Increased pxt-core version for timely support.
Additionally, there is a change in the programming language switch.
A visual bug could appear at different scales.
#editortoggle.ui.grid.padded it may be a little more than 45 in height, but the background fill element (.ui.item.toggle.dropdown-attached) is always 45. I changed its height to 100%.
after
> Pxt core bump 9.1.1x and more
