microsoft/pxt-ev3

libs/core/input.ts

Related to #847 
Fixes bug with multiple sensors, now second sensor need fewer than 3 seconds to start
It is much better than it was

Fixed multiple sensor bug

---

docs/design-engineering/make-it-smarter.md

1500 milliseconds is not one quarter of a second - fixed the text to reflect.

Fix typos in sample programme description

---

libs/core/buttons.ts
libs/core/linux.cpp

Add exitThread() polling the exit button

---

docs/reference/motors/synced/steer.md
docs/reference/motors/synced/tank.md
libs/core/input.ts
libs/core/output.ts
sim/state/motornode.ts

Fix for https://github.com/microsoft/pxt-ev3/issues/844

Tank fixes

---

docs/reference/motors/synced/tank.md
docs/tutorials/coast-or-brake.md
docs/tutorials/motors.md
docs/tutorials/pause-until-pressed.md
docs/tutorials/pivot-turn.md
docs/tutorials/reflected-light-calibration.md
docs/tutorials/reflected-light-measure.md
docs/tutorials/smooth-turn.md
docs/tutorials/spin-turn.md
docs/tutorials/tank-zigzag.md

Throw in some edits to the new examples.
RE: #894, #895, #896

  Some edits for the new sensor/motor examples

---

docs/reference/brick/battery-property.md
libs/core/battery.ts
libs/core/input.ts
libs/ev3/ns.ts

battery properties

---

docs/tutorials/city-shaper/robot-1.md
docs/tutorials/city-shaper/robot-2.md

Few edits for the robot 1 and 2 tutorials.
Note: the field editors for steer() and setBrake() are different...`ports` vs. `motors`...showing either **B+C** and **BC** for the same port instance.
RE: #907

Edits for crane mission robot tutorials

---

libs/broadcast/broadcast.ts
libs/broadcast/pxt.json
libs/ev3/ns.ts
pxtarget.json

broadcast project

---

fieldeditors/field_speed.ts
libs/core/output.ts

Snap backwards

---

docs/reference/brick/show-ports.md
docs/reference/motors/reset-all.md
docs/reference/motors/stop-all.md
libs/color-sensor/color.ts
libs/core/output.ts
libs/gyro-sensor/docs/reference/sensors/gyro/compute-drift.md
libs/gyro-sensor/docs/reference/sensors/gyro/drift.md
libs/gyro-sensor/gyro.ts
libs/tests/targetoverrides.ts

Drift support

---

editor/deploy.ts
editor/extension.ts
fieldeditors/field_speed.ts
libs/gyro-sensor/gyro.ts
package.json

Restart download immeidately once paired.

Better bt download flow

---

docs/labview.md
docs/reference/motors/synced/steer.md
editor/deploy.ts
editor/extension.ts
editor/wrap.ts
fieldeditors/field_turnratio.ts

web serial cleanup

---

docs/reference/brick/exit-program.md
docs/reference/brick/stop-program.md
libs/core/battery.ts
libs/core/buttons.ts
libs/ev3/brick.ts
libs/ev3/ns.ts
libs/ev3/pxt.json

Stopping the program running on the brick is a common task. Add a top level block in brick.

add block to stop program

---

libs/ev3/startup.ts
libs/screen/targetoverrides.ts

if no screen function is used, use showports

Boot sequence

---

docs/reference/brick/exit-program.md
fieldeditors/field_motors.ts
libs/core/battery.ts
libs/core/buttons.ts
libs/core/input.ts
libs/core/output.ts
libs/ev3/brick.ts
libs/ev3/ns.ts
libs/ev3/pxt.json
libs/ev3/startup.ts
libs/screen/targetoverrides.ts
sim/state/motornode.ts
sim/state/output.ts

Port various updates from master in stable1.2

Pulling updates from master

---

docs/offline-app.html
targetconfig.json

Keeping Electron in sync with master.

update elecron version to 1.2.26

---

libs/music/music.cpp

I noticed that volume is only responsible for values ~0-15. Above 15 is not louder anymore (and TBH it's loud already). Then I found this repo: https://github.com/mindboards/ev3sources which guided me to sound levels (1-8 and 1-13) insted of raw volume (0-100%).

Change sound volume to level

---

docs/reference/control/wait-micros.md
sim/state/motornode.ts

Make a few word changes to reduce Policheck hits.

Word changes to reduce policheck hits

---

.github/workflows/pxt-buildmain.yml
.github/workflows/pxt-buildpr.yml
.github/workflows/pxt-buildpush.yml
.travis.yml

Draft until I have the secrets set up correctly

Adding gh-actions workflows

---

pxtarget.json

Change crowdin project to new name (kindscript->makecode)

---

pxtarget.json

Enable addNewTypeScriptFile so that you can split your code into multiple files. Enable blocksCollapsing to collapse blocks for convenience. Turn off highContrast it doesn't work now. We'll see later...
All enabled options work.

Enable some features to improve the programming experience

---

editor/deploy.ts
editor/extension.ts
fieldeditors/extension.ts
package.json

Testing the new crowdin v2 support

Bump core to grab the new crowdin changes
